'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ArrendamientoDetalle

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''txtTasaCalculadaMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTasaCalculadaMensual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdEstatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdDirRH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdDirRH As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdDirNegocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdDirNegocio As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdDirFinanzas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdDirFinanzas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tblEstatus0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEstatus0 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblEstatus0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstatus0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsuarioRegistro0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsuarioRegistro0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAutorizaciones0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaciones0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumero0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumero0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEmpresa0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpresa0 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCategoriaArrendamiento0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoriaArrendamiento0 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDepartamento0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartamento0 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEmpleado0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpleado0 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPrecioGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrecioGE As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''phTipoAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phTipoAuto As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''txtComentariosAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComentariosAuto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblGeneral As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsuarioRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsuarioRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAutosHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAutosHeader1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblPrecioGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrecioGE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAutosHeader2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAutosHeader2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblTipoAuto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoAuto1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAutosHeader3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAutosHeader3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblComentariosAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComentariosAuto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAutorizaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtContratoMaestro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContratoMaestro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCategoriaArrendamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoriaArrendamiento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trAutos1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAutos1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFolio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlArrendadora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArrendadora As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tdMaquinariaTecnologia1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMaquinariaTecnologia1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdMaquinariaTecnologia2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMaquinariaTecnologia2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''txtAnexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnexo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dtFechaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaInicio As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ddlDiaPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDiaPago As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dtFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaFin As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtTasa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTasa As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddlDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartamento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpleado As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trFlotilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFlotilla As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblFlotilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlotilla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFlotilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlotilla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblDetalle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetalle1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtMarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNoSerie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoSerie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tblDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetalle2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtNumFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumFactura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProveedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProveedor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCantidadDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCantidadDetalle2 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtMontoUnitarioDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoUnitarioDetalle2 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblMontoTotalDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoTotalDetalle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMontoTotalDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoTotalDetalle2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDescripcionDetalle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionDetalle2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlPeriodicidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPeriodicidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumeroParcialidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroParcialidades As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtMontoTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoTotal As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtMontoParcialidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoParcialidades As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtComision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComision As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddlMoneda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoneda As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDepositoGarantia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepositoGarantia As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblArrendamientoNeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrendamientoNeto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAutos2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAutos2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtValorResidual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorResidual As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtValorRescate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorRescate As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblValorFuturo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValorFuturo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTasaCalculadaMensual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTasaCalculadaMensual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTasaCalculadaAnual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTasaCalculadaAnual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAseguradora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAseguradora As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dtFechaInicioSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaInicioSeguro As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeguro As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''dtFechaFinSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaFinSeguro As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtNumPoliza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPoliza As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlazoSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlazoSeguro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlazoSeguroHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlazoSeguroHidden As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlPeriodicidadSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPeriodicidadSeguro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtParcialidadSeguro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParcialidadSeguro As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''dtFechaRecepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaRecepcion As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtRecibidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecibidoPor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEliminar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAutorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutorizar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechazar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblArchivos As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''divArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArchivos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtIdArrendamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdArrendamiento As Global.System.Web.UI.WebControls.TextBox
End Class
