<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/DefaultMP.Master" CodeBehind="AsuetosBusqueda.aspx.vb" Inherits="Intranet.AsuetosBusqueda" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server"></telerik:RadScriptManager>

    <asp:Panel ID="pnlBusqueda" runat="server">
        <table cellpadding="0" cellspacing="0" border="0" width="600px">
            <tr>
                <td colspan="3"><span style="font-size:15px; font-weight:bold;">Catálogo de Asuetos</span><hr style="margin:0; padding:0;" /></td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;&nbsp;Seleccione un año:</td>
                <td><asp:DropDownList ID="ddlAnio" runat="server" AutoPostBack="true"></asp:DropDownList></td>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;&nbsp;Pais:</td>
                <td>
                    <asp:DropDownList ID="ddlPais" runat="server" AutoPostBack="true">
                        <asp:ListItem Value="1" Text="Mexico"></asp:ListItem>
                        <asp:ListItem Value="2" Text="USA"></asp:ListItem>
                        <asp:ListItem Value="3" Text="España"></asp:ListItem>
                    </asp:DropDownList>
                </td>
                <td>
                    <asp:Button ID="btnAgregar" runat="server" Text="Agregar" CssClass="botones" />
                </td>
            </tr>
        </table>
    </asp:Panel>
    <br />
    <div id="divNuevo" runat="server" style="width:630px">
        <table>
            <tr>
                <td colspan="2">Ingrese los datos del nuevo Asueto</td>
            </tr>
            <tr>
                <td>Descripción</td>
                <td><asp:TextBox ID="txtDescripcion" runat="server" Width="200px" MaxLength="256"></asp:TextBox></td>
            </tr>
            <tr>
                <td>Fecha</td>
                <td>
                    <telerik:RadDatePicker ID="dtFecha" runat="server" DateInput-DateFormat="dd/MM/yyyy" DateInput-DisplayDateFormat="dd/MM/yyyy" Width="100px" MinDate="2013/01/01"></telerik:RadDatePicker>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><asp:CheckBox ID="chkMedioDia" runat="server" Text="Asueto de medio dia?" /></td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="btnGuardar" runat="server" Text="Guardar" CssClass="botones" />
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnCancelar" runat="server" Text="Salir" CssClass="botones" />
                </td>
            </tr>
        </table>
    </div>
    <asp:GridView ID="gvResultados" runat="server" CssClass="grid" Width="630px" 
         EmptyDataText="No se encontraron resultados para la busqueda realizada" AutoGenerateColumns="False" 
         AllowSorting="false" AllowPaging="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false"
         DataKeyNames="id_asueto" PageSize="50">
         <HeaderStyle CssClass="grid_header" />
         <AlternatingRowStyle CssClass="grid_alternating" />
          <Columns>
              <asp:TemplateField HeaderText="Fecha" SortExpression="fecha">
                    <ItemTemplate>
                            <asp:Label ID="lblFecha" runat="server" Text='<%# Bind("fecha","{0:dd/MM/yyyy}") %>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Descripción" SortExpression="descripcion">
                    <ItemTemplate>
                            <asp:Label ID="lblDescripcion" runat="server" Text='<%# Bind("descripcion")%>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Medio Dia?" SortExpression="medio_dia">
                    <ItemTemplate>
                            <asp:Label ID="lblMedioDia" runat="server" Text='<%# Bind("medio_dia")%>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Acciones">
                  <ItemTemplate>
                      <div align="center">
                          <asp:ImageButton ID="btnEliminar" runat="server" ImageUrl="/images/delete.png" CommandName="eliminar" ToolTip="Eliminar" CommandArgument='<%# Bind("id_asueto")%>' OnClientClick="return confirm('Seguro que desea eliminar este asueto?\nEsto regresara 1 dia a aquellas solicitudes de vacaciones que aun no sean verificadas por nominas.');" />
                      </div>
                  </ItemTemplate>
              </asp:TemplateField>
          </Columns>
    </asp:GridView>

</asp:Content>
