'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AutorizacionesConfig

    '''<summary>
    '''pnlBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBusqueda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstEmpleadosProyectManagersDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosProyectManagersDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnProyectManagersLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProyectManagersLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnProyectManagersRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProyectManagersRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstEmpleadosProyectManagersAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosProyectManagersAsignados As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''tblEmpleadosVer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmpleadosVer As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lstEmpleadosContabilidadDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosContabilidadDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnContabilidadLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContabilidadLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnContabilidadRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContabilidadRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstEmpleadosContabilidadAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosContabilidadAsignados As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lstEmpleadosNominasDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosNominasDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnNominasLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNominasLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnNominasRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNominasRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstEmpleadosNominasAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosNominasAsignados As Global.System.Web.UI.WebControls.ListBox
End Class
