<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/DefaultMP.Master" CodeBehind="CategoriaAvisoBusqueda.aspx.vb" Inherits="Intranet.CategoriaAvisoBusqueda" %>

<%@ Import Namespace="Intranet.LocalizationIntranet" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <asp:Panel ID="pnlBusqueda" runat="server">
        <table cellpadding="0" cellspacing="0" border="0" width="600px">
            <tr>
                <td><span style="font-size:15px; font-weight:bold;"><%=TranslateLocale.text("Catalogo de Conceptos de Avisos")%></span><hr style="margin:0; padding:0;" /></td>
            </tr>
            <tr>
                <td>
                    <asp:Button ID="btnAgregar" runat="server" Text="Agregar Nuevo Concepto" CssClass="botones" />
                </td>
            </tr>
        </table>
    </asp:Panel>
    <br /><br />
    <div id="divNuevo" runat="server" style="width:630px">
        <table>
            <tr>
                <td colspan="5"><%=Translatelocale.text("Ingrese los datos del nuevo Concepto")%></td>
            </tr>
            <tr>
                <td><%=TranslateLocale.text("Descripción")%>:</td>
                <td><asp:TextBox ID="txtDescripcion" runat="server" Width="200px" MaxLength="256"></asp:TextBox></td>
            </tr>
            <tr>
                <td><%=TranslateLocale.text("Descripción ingles")%>:</td>
                <td><asp:TextBox ID="txtDescripcionEn" runat="server" Width="200px" MaxLength="256"></asp:TextBox></td>
            </tr>
            <tr>
                <td colspan="2"><br />
                    <asp:Button ID="btnGuardar" runat="server" Text="Guardar" CssClass="botones" />
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnCancelar" runat="server" Text="Salir" CssClass="botones" />
                </td>
            </tr>
        </table>
    </div>
    <asp:GridView ID="gvResultados" runat="server" CssClass="grid" Width="630px" 
         EmptyDataText="No se encontraron resultados para la busqueda realizada" AutoGenerateColumns="False" 
         AllowSorting="True" AllowPaging="true" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false"
         DataKeyNames="id_categoria">
         <HeaderStyle CssClass="grid_header" />
         <AlternatingRowStyle CssClass="grid_alternating" />
          <Columns>
              <asp:TemplateField HeaderText="Descripción" SortExpression="descripcion">
                    <ItemTemplate>
                            <asp:Label ID="lblDescripcion" runat="server" Text='<%# Bind("descripcion")%>' />
                            <asp:TextBox id="txtDescripcion" runat="server" text='<%# Bind("descripcion")%>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>
              <asp:TemplateField HeaderText="Descripción ingles" SortExpression="descripcion_en">
                    <ItemTemplate>
                            <asp:Label ID="lblDescripcionEn" runat="server" Text='<%# Bind("descripcion_en")%>' />
                            <asp:TextBox id="txtDescripcionEn" runat="server" text='<%# Bind("descripcion_en")%>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>
              <asp:TemplateField HeaderText="Acciones">
                  <ItemTemplate>
                      <div align="center">
                          <asp:ImageButton ID="btnEdit" runat="server" ImageUrl="/images/edit.png" CommandName="edit" ToolTip="Editar" CommandArgument='<%# Bind("id_categoria")%>' />
                          &nbsp;
                          <asp:ImageButton ID="btnDelete" runat="server" ImageUrl="/images/delete.png" CommandName="eliminar" ToolTip="Eliminar" CommandArgument='<%# Bind("id_categoria")%>' OnClientClick="return confirm('Seguro que desea eliminar este registro?');" />
                          &nbsp;
                          <asp:ImageButton ID="btnSave" runat="server" ImageUrl="/images/save.png" CommandName="save" Visible="false" ToolTip="Guardar" CommandArgument='<%# Bind("id_categoria")%>' />
                          &nbsp;
                          <asp:ImageButton ID="btnCancel" runat="server" ImageUrl="/images/cancel.png" CommandName="cancel" Visible="false" ToolTip="Cancelar" />
                      </div>
                  </ItemTemplate>
              </asp:TemplateField>
          </Columns>
    </asp:GridView>

</asp:Content>
