<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/DefaultMP_Wide.Master" CodeBehind="DepartamentosBusqueda.aspx.vb" Inherits="Intranet.DepartamentosBusqueda" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <asp:Panel ID="pnlBusqueda" runat="server" DefaultButton="btnBuscar">
        <table cellpadding="0" cellspacing="0" border="0" width="700px">
            <tr>
                <td colspan="3"><span style="font-size:15px; font-weight:bold;">Catalogo de Departamentos</span><hr style="margin:0; padding:0;" /></td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;&nbsp;Ingrese el texto de busqueda:</td>
                <td><asp:TextBox ID="txtBusqueda" runat="server" Width="120px"></asp:TextBox></td>
                <td>
                    <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="botones" />
                    &nbsp;&nbsp;
                    <%--<asp:Button ID="btnAgregar" runat="server" Text="Agregar" CssClass="botones" />--%>
                </td>
            </tr>
        </table>
    </asp:Panel>
    <br />
    <div id="divNuevo" runat="server" style="width:730px">
        <table>
            <tr>
                <td colspan="2">Ingrese los datos del nuevo Departamento</td>
            </tr>
            <tr>
                <td>Departamento</td>
                <td><asp:TextBox ID="txtDepartamentoNuevo" runat="server" Width="200px" MaxLength="256"></asp:TextBox></td>
            </tr>
            <tr>
                <td>Clave</td>
                <td><asp:TextBox ID="txtClaveNuevo" runat="server" Width="60px" MaxLength="8"></asp:TextBox></td>
            </tr>
            <tr>
                <td>Empresa</td>
                <td><asp:DropDownList ID="ddlEmpresaNuevo" runat="server"></asp:DropDownList></td>
            </tr>
            <tr>
                <td>Director de Area</td>
                <td><asp:DropDownList ID="ddlDirectorAreaNuevo" runat="server"></asp:DropDownList></td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Button ID="btnGuardar" runat="server" Text="Guardar" CssClass="botones" />
                    &nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnCancelar" runat="server" Text="Salir" CssClass="botones" />
                </td>
            </tr>
        </table>
    </div>
    <asp:GridView ID="gvResultados" runat="server" CssClass="grid" Width="730px" 
         EmptyDataText="No se encontraron resultados para la busqueda realizada" AutoGenerateColumns="False" 
         AllowSorting="True" AllowPaging="true" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false"
         DataKeyNames="id_departamento" PageSize="15">
         <HeaderStyle CssClass="grid_header" />
         <AlternatingRowStyle CssClass="grid_alternating" />
          <Columns>
              <asp:TemplateField HeaderText="Clave" SortExpression="centro_costo">
                    <ItemTemplate>
                            <asp:Label ID="lblClave" runat="server" Text='<%# Bind("centro_costo")%>' />
                            <asp:TextBox id="txtClave" runat="server" text='<%# Bind("centro_costo")%>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Departamento" SortExpression="nombre">
                    <ItemTemplate>
                            <asp:Label ID="lblDepartamento" runat="server" Text='<%# Bind("nombre") %>' />
                            <asp:TextBox id="txtDepartamento" runat="server" text='<%# Bind("nombre") %>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>              
<%--              <asp:TemplateField HeaderText="Empresa" SortExpression="empresa">
                    <ItemTemplate>
                            <asp:Label ID="lblEmpresa" runat="server" Text='<%# Bind("empresa")%>' />
                            <asp:DropDownList ID="ddlEmpresa" runat="server" Visible="false"></asp:DropDownList>
                            <asp:TextBox id="txtIdEmpresa" runat="server" text='<%# Bind("id_empresa") %>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>              --%>
<%--              <asp:TemplateField HeaderText="Director" SortExpression="director">
                    <ItemTemplate>
                            <asp:Label ID="lblDirectorArea" runat="server" Text='<%# Bind("director")%>' />
                            <asp:DropDownList ID="ddlDirectorArea" runat="server" Visible="false"></asp:DropDownList>
                            <asp:TextBox id="txtIdDirectorArea" runat="server" text='<%# Bind("id_empleado_director")%>' Visible="false" />
                    </ItemTemplate>
              </asp:TemplateField>              --%>
<%--              <asp:TemplateField HeaderText="Acciones">
                  <ItemTemplate>
                      <div align="center">
                          <asp:ImageButton ID="btnEdit" runat="server" ImageUrl="/images/edit.png" CommandName="edit" ToolTip="Editar" CommandArgument='<%# Bind("id_departamento")%>' />
                          <asp:ImageButton ID="btnSave" runat="server" ImageUrl="/images/save.png" CommandName="save" Visible="false" ToolTip="Guardar" CommandArgument='<%# Bind("id_departamento")%>' />
                          &nbsp;&nbsp;&nbsp;
                          <asp:ImageButton ID="btnCancel" runat="server" ImageUrl="/images/cancel.png" CommandName="cancel" Visible="false" ToolTip="Cancelar" />
                      </div>
                  </ItemTemplate>
              </asp:TemplateField>--%>
          </Columns>
    </asp:GridView>

</asp:Content>
