'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GruposMiembros

    '''<summary>
    '''pnlBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBusqueda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGrupoNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrupoNombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstEmpleadosPublicanDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosPublicanDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnPublicanLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPublicanLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnPublicanRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPublicanRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstEmpleadosPublicanAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosPublicanAsignados As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''tblEmpleadosVer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmpleadosVer As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lstEmpleadosVenDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosVenDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnVenLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVenLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnVenRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVenRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstEmpleadosVenAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleadosVenAsignados As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''tblDepartamentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDepartamentos As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lstDepartamentosVenDisponibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDepartamentosVenDisponibles As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnDepLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDepLeft As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDepRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDepRight As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lstDepartamentosVenAsignados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDepartamentosVenAsignados As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId As Global.System.Web.UI.WebControls.TextBox
End Class
