'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ParametrosGenerales

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''pnlBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBusqueda As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlIdUsuarioPagosNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioPagosNC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioPagosNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioPagosNB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioPagosNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioPagosNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDiasVencimientoIntranet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasVencimientoIntranet As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtDiasVencimientoNomina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasVencimientoNomina As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txtMontoMaximoMateriales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoMaximoMateriales As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddlIdUsuarioOperacionesNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioOperacionesNC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioOperacionesNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioOperacionesNB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioOperacionesNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioOperacionesNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMontoMaximoComidasInternas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoMaximoComidasInternas As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''ddlIdUsuarioComidasInternasNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioComidasInternasNC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioComidasInternasNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioComidasInternasNB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioComidasInternasNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioComidasInternasNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorNS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorNS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorNB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorNE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorNE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorNU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorNU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorFinanzasNS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorFinanzasNS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorFinanzasNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorFinanzasNB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorFinanzasNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorFinanzasNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorFinanzasNE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorFinanzasNE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorFinanzasNU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorFinanzasNU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioDirectorRH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioDirectorRH As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioAutorizaMateriales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioAutorizaMateriales As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlIdUsuarioVerificaVacacionesGuardiasSeguridadNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdUsuarioVerificaVacacionesGuardiasSeguridadNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEmailsNotificacionDatosTelefonia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailsNotificacionDatosTelefonia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvConfiguracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvConfiguracion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
End Class
