<%@ Page Language="vb" AutoEventWireup="false" MasterPageFile="~/DefaultMP_Wide.Master" CodeBehind="RecibosNominaBloqueados.aspx.vb" Inherits="Intranet.RecibosNominaBloqueados" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <table cellpadding="0" cellspacing="0" border="0" width="700px">
        <tr>
            <td colspan="3"><span style="font-size:15px; font-weight:bold;">Desbloqueo de Recibos de Nomina</span><hr style="margin:0; padding:0;" /></td>
        </tr>
    </table>
    <br />
    <asp:GridView ID="gvResultados" runat="server" CssClass="grid" Width="730px" 
         EmptyDataText="No se encontraron recibos de nomina bloqueados" AutoGenerateColumns="False" 
         AllowSorting="false" AllowPaging="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false"
          PageSize="999">
         <HeaderStyle CssClass="grid_header" />
         <AlternatingRowStyle CssClass="grid_alternating" />
          <Columns>
              <asp:TemplateField HeaderText="Numero">
                    <ItemTemplate>
                            <asp:Label ID="lblNumero" runat="server" Text='<%# Bind("numero")%>' />
                            <asp:Label ID="lblParamAnio" runat="server" Text='<%# Bind("anio")%>' />
                            <asp:Label ID="lblParamPeriodo" runat="server" Text='<%# Bind("periodo")%>' />
                            <asp:Label ID="lblParamEmpleado" runat="server" Text='<%# Bind("id_empleado")%>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Nombre">
                    <ItemTemplate>
                            <asp:Label ID="lblNombre" runat="server" Text='<%# Bind("nombre") %>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Empresa" >
                    <ItemTemplate>
                            <asp:Label ID="lblEmpresa" runat="server" Text='<%# Bind("empresa")%>' />
                    </ItemTemplate>
              </asp:TemplateField>              
              <asp:TemplateField HeaderText="Recibo Bloqueado">
                    <ItemTemplate>
                            <asp:Label ID="lblQuincena" runat="server" Text='<%# Bind("quincena")%>' /> / 
                            <asp:Label ID="blAnio" runat="server" Text='<%# Bind("anio")%>' />
                    </ItemTemplate>
              </asp:TemplateField>
              <asp:TemplateField HeaderText="Acciones">
                  <ItemTemplate>
                      <div align="center">
                          <asp:LinkButton ID="btnDesbloquear" runat="server" Text="Desbloquear" OnClientClick="return confirm('Seguro que desea desbloquear este recibo');" CommandName="desbloquear" CommandArgument='<%# Bind("anio") & "|" & Bind("periodo") & "|" & Bind("id_empleado") %>'></asp:LinkButton>
                      </div>
                  </ItemTemplate>
              </asp:TemplateField>
          </Columns>
    </asp:GridView>

</asp:Content>
