'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RepFinancierosPronosticoCaptura
    
    '''<summary>
    '''ddlReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReporte As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEmpresa As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpresa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAnio As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnContinuar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinuar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMensajeEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeEstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCaptura As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCaptura As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvCapturaER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCapturaER As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvCapturaERIndividual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCapturaERIndividual As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvCapturaExtendido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCapturaExtendido As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divDistribucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDistribucion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNombreConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreConcepto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtIdConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdConcepto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFibras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFibras As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHornos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHornos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkFibrasAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFibrasAuto As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkHornosAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHornosAuto As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtFibrasTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasPorAsignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasPorAsignar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosPorAsignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosPorAsignar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFibrasMes12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFibrasMes12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHornosMes12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHornosMes12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnGuardaDistribucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardaDistribucion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstatus As Global.System.Web.UI.WebControls.TextBox
End Class
