'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RepFinancierosCuadreInterImpresion

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''divReporteNormal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReporteNormal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ExportToExcel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportToExcel1 As Global.KrishLabs.Web.Controls.ExportToExcel

    '''<summary>
    '''gvCapturaCuadreInter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCapturaCuadreInter As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblTituloInterRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloInterRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExportToExcel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportToExcel2 As Global.KrishLabs.Web.Controls.ExportToExcel

    '''<summary>
    '''gvCapturaCuadreInterRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCapturaCuadreInterRef As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divReporteSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReporteSum As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ExportToExcel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportToExcel3 As Global.KrishLabs.Web.Controls.ExportToExcel

    '''<summary>
    '''gvSumarizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSumarizado As Global.System.Web.UI.WebControls.GridView
End Class
