'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SolicitudGastosImprimir

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''txtIdEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdEmpresa As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdSolicitud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtIdEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdEmpleado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPendienteAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendienteAuth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaSolicitud As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolicitante As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblViajero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViajero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaComprobacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaComprobacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaIni As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaFin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''diasViaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diasViaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMontoPesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoPesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMontoUSD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoUSD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMontoEuros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoEuros As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDestino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDestino As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMotivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSolicitudConMateriales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSolicitudConMateriales As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFolioSolicitudReposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolioSolicitudReposicion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divComprobantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComprobantes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvConceptos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvConceptos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblAutorizaJefe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaJefe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAutorizaConta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaConta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAutorizaJefeComprobacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaJefeComprobacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAutorizaContaComprobacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutorizaContaComprobacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''oculta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oculta1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tablaResumenColTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tablaResumenColTE As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tablaResumenColCav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tablaResumenColCav As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''phResumenFormaPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phResumenFormaPago As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblTotalConvertido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalConvertido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalGastosConvPesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGastosConvPesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGastosTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGastosTC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalGastos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGastos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalGastosPesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGastosPesos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDiasViaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasViaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGastoDiarioPromedio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGastoDiarioPromedio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnticipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnticipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoAnticipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoAnticipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalViaticos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalViaticos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoViaticos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoViaticos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalCompraMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalCompraMaterial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoMateriales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoMateriales As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalAjustado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalAjustado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoAjustado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoAjustado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoTexto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoTexto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaldoSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoSaldo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblTicketEmpresarial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTicketEmpresarial As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblTESaldoInicialLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTESaldoInicialLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTESaldoInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTESaldoInicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTEAnticipoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTEAnticipoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTEAnticipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTEAnticipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTERetirosLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTERetirosLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTERetiros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTERetiros As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTESaldoFinalLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTESaldoFinalLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTESaldoFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTESaldoFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRealizarRetiroTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRealizarRetiroTE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblRetiroTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblRetiroTE As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblSaldoActualTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaldoActualTE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtImporteRetiroTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImporteRetiroTE As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''btnProcesarRetiroTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProcesarRetiroTE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelarRetiroTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelarRetiroTE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divPoliza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPoliza As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnTituloPoliza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnTituloPoliza As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvPoliza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPoliza As Global.System.Web.UI.WebControls.GridView
End Class
