'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SolicitudGastos

    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divMisTareas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMisTareas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSolicitudesAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolicitudesAuth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSolicitudesAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitudesAuth As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dpSolicitudesAuthTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesAuthTop As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''lvSolicitudesAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSolicitudesAuth As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dpSolicitudesAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesAuth As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''divGastosPorComprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGastosPorComprobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSolicitudesPorComprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolicitudesPorComprobar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSolicitudesPorComprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitudesPorComprobar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dpSolicitudesPorComprobarTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesPorComprobarTop As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''lvSolicitudesPorComprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSolicitudesPorComprobar As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dpSolicitudesPorComprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesPorComprobar As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''divMisSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMisSolicitudes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolicitudes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitudes As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dpSolicitudesTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesTop As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''lvSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSolicitudes As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dpSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudes As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''divRealizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRealizado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtSolicitudesRealizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolicitudesRealizado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSolicitudesRealizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitudesRealizado As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''dpSolicitudesRealizadoTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesRealizadoTop As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''lvSolicitudesRealizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSolicitudesRealizado As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''dpSolicitudesRealizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpSolicitudesRealizado As Global.System.Web.UI.WebControls.DataPager
End Class
