'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ServicioEdenred
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_ITEService", [Namespace]:="urn:ERMX.Services")>  _
    Partial Public Class BasicHttpBinding_ITEService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CardBalanceAssignmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CardBalanceAdjustmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CardGetListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestToConsumeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IntranetTest.My.MySettings.Default.IntranetTest_ServicioEdenred_TEService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CardBalanceAssignmentCompleted As CardBalanceAssignmentCompletedEventHandler
        
        '''<remarks/>
        Public Event CardBalanceAdjustmentCompleted As CardBalanceAdjustmentCompletedEventHandler
        
        '''<remarks/>
        Public Event CardGetListCompleted As CardGetListCompletedEventHandler
        
        '''<remarks/>
        Public Event TestToConsumeCompleted As TestToConsumeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardBalanceAssignment", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardBalanceAssignment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardBalanceAssignmentRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardBalanceAssignmentResponse
            Dim results() As Object = Me.Invoke("CardBalanceAssignment", New Object() {request})
            Return CType(results(0),CardBalanceAssignmentResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAssignmentAsync(ByVal request As CardBalanceAssignmentRequest)
            Me.CardBalanceAssignmentAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAssignmentAsync(ByVal request As CardBalanceAssignmentRequest, ByVal userState As Object)
            If (Me.CardBalanceAssignmentOperationCompleted Is Nothing) Then
                Me.CardBalanceAssignmentOperationCompleted = AddressOf Me.OnCardBalanceAssignmentOperationCompleted
            End If
            Me.InvokeAsync("CardBalanceAssignment", New Object() {request}, Me.CardBalanceAssignmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardBalanceAssignmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardBalanceAssignmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardBalanceAssignmentCompleted(Me, New CardBalanceAssignmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardBalanceAdjustment", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardBalanceAdjustment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardBalanceAdjustmentRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardBalanceAdjustmentResponse
            Dim results() As Object = Me.Invoke("CardBalanceAdjustment", New Object() {request})
            Return CType(results(0),CardBalanceAdjustmentResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAdjustmentAsync(ByVal request As CardBalanceAdjustmentRequest)
            Me.CardBalanceAdjustmentAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAdjustmentAsync(ByVal request As CardBalanceAdjustmentRequest, ByVal userState As Object)
            If (Me.CardBalanceAdjustmentOperationCompleted Is Nothing) Then
                Me.CardBalanceAdjustmentOperationCompleted = AddressOf Me.OnCardBalanceAdjustmentOperationCompleted
            End If
            Me.InvokeAsync("CardBalanceAdjustment", New Object() {request}, Me.CardBalanceAdjustmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardBalanceAdjustmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardBalanceAdjustmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardBalanceAdjustmentCompleted(Me, New CardBalanceAdjustmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardGetList", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardGetList(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardGetListRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardGetListResponse
            Dim results() As Object = Me.Invoke("CardGetList", New Object() {request})
            Return CType(results(0),CardGetListResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardGetListAsync(ByVal request As CardGetListRequest)
            Me.CardGetListAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardGetListAsync(ByVal request As CardGetListRequest, ByVal userState As Object)
            If (Me.CardGetListOperationCompleted Is Nothing) Then
                Me.CardGetListOperationCompleted = AddressOf Me.OnCardGetListOperationCompleted
            End If
            Me.InvokeAsync("CardGetList", New Object() {request}, Me.CardGetListOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardGetListOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardGetListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardGetListCompleted(Me, New CardGetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/TestToConsume", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestToConsume(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As TestRequestDTO) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BaseResponse
            Dim results() As Object = Me.Invoke("TestToConsume", New Object() {request})
            Return CType(results(0),BaseResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestToConsumeAsync(ByVal request As TestRequestDTO)
            Me.TestToConsumeAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestToConsumeAsync(ByVal request As TestRequestDTO, ByVal userState As Object)
            If (Me.TestToConsumeOperationCompleted Is Nothing) Then
                Me.TestToConsumeOperationCompleted = AddressOf Me.OnTestToConsumeOperationCompleted
            End If
            Me.InvokeAsync("TestToConsume", New Object() {request}, Me.TestToConsumeOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestToConsumeOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestToConsumeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestToConsumeCompleted(Me, New TestToConsumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    'CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpsBinding_ITEService", [Namespace]:="urn:ERMX.Services")>  _
    Partial Public Class BasicHttpsBinding_ITEService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CardBalanceAssignmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CardBalanceAdjustmentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CardGetListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestToConsumeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://demo.edenred.com.mx/Desarrollo/TEServicesFacade/TEService.svc"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CardBalanceAssignmentCompleted As CardBalanceAssignmentCompletedEventHandler
        
        '''<remarks/>
        Public Event CardBalanceAdjustmentCompleted As CardBalanceAdjustmentCompletedEventHandler
        
        '''<remarks/>
        Public Event CardGetListCompleted As CardGetListCompletedEventHandler
        
        '''<remarks/>
        Public Event TestToConsumeCompleted As TestToConsumeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardBalanceAssignment", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardBalanceAssignment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardBalanceAssignmentRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardBalanceAssignmentResponse
            Dim results() As Object = Me.Invoke("CardBalanceAssignment", New Object() {request})
            Return CType(results(0),CardBalanceAssignmentResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAssignmentAsync(ByVal request As CardBalanceAssignmentRequest)
            Me.CardBalanceAssignmentAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAssignmentAsync(ByVal request As CardBalanceAssignmentRequest, ByVal userState As Object)
            If (Me.CardBalanceAssignmentOperationCompleted Is Nothing) Then
                Me.CardBalanceAssignmentOperationCompleted = AddressOf Me.OnCardBalanceAssignmentOperationCompleted
            End If
            Me.InvokeAsync("CardBalanceAssignment", New Object() {request}, Me.CardBalanceAssignmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardBalanceAssignmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardBalanceAssignmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardBalanceAssignmentCompleted(Me, New CardBalanceAssignmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardBalanceAdjustment", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardBalanceAdjustment(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardBalanceAdjustmentRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardBalanceAdjustmentResponse
            Dim results() As Object = Me.Invoke("CardBalanceAdjustment", New Object() {request})
            Return CType(results(0),CardBalanceAdjustmentResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAdjustmentAsync(ByVal request As CardBalanceAdjustmentRequest)
            Me.CardBalanceAdjustmentAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardBalanceAdjustmentAsync(ByVal request As CardBalanceAdjustmentRequest, ByVal userState As Object)
            If (Me.CardBalanceAdjustmentOperationCompleted Is Nothing) Then
                Me.CardBalanceAdjustmentOperationCompleted = AddressOf Me.OnCardBalanceAdjustmentOperationCompleted
            End If
            Me.InvokeAsync("CardBalanceAdjustment", New Object() {request}, Me.CardBalanceAdjustmentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardBalanceAdjustmentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardBalanceAdjustmentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardBalanceAdjustmentCompleted(Me, New CardBalanceAdjustmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/CardGetList", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CardGetList(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As CardGetListRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> CardGetListResponse
            Dim results() As Object = Me.Invoke("CardGetList", New Object() {request})
            Return CType(results(0),CardGetListResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CardGetListAsync(ByVal request As CardGetListRequest)
            Me.CardGetListAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CardGetListAsync(ByVal request As CardGetListRequest, ByVal userState As Object)
            If (Me.CardGetListOperationCompleted Is Nothing) Then
                Me.CardGetListOperationCompleted = AddressOf Me.OnCardGetListOperationCompleted
            End If
            Me.InvokeAsync("CardGetList", New Object() {request}, Me.CardGetListOperationCompleted, userState)
        End Sub
        
        Private Sub OnCardGetListOperationCompleted(ByVal arg As Object)
            If (Not (Me.CardGetListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CardGetListCompleted(Me, New CardGetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ERMX.Services/ITEService/TestToConsume", RequestNamespace:="urn:ERMX.Services", ResponseNamespace:="urn:ERMX.Services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestToConsume(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As TestRequestDTO) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> BaseResponse
            Dim results() As Object = Me.Invoke("TestToConsume", New Object() {request})
            Return CType(results(0),BaseResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestToConsumeAsync(ByVal request As TestRequestDTO)
            Me.TestToConsumeAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestToConsumeAsync(ByVal request As TestRequestDTO, ByVal userState As Object)
            If (Me.TestToConsumeOperationCompleted Is Nothing) Then
                Me.TestToConsumeOperationCompleted = AddressOf Me.OnTestToConsumeOperationCompleted
            End If
            Me.InvokeAsync("TestToConsume", New Object() {request}, Me.TestToConsumeOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestToConsumeOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestToConsumeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestToConsumeCompleted(Me, New TestToConsumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Request")>  _
    Partial Public Class CardBalanceAssignmentRequest
        
        Private cardBalanceDTOListField() As CardBalanceDTO
        
        Private securityField As SecurityDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property CardBalanceDTOList() As CardBalanceDTO()
            Get
                Return Me.cardBalanceDTOListField
            End Get
            Set
                Me.cardBalanceDTOListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Security() As SecurityDTO
            Get
                Return Me.securityField
            End Get
            Set
                Me.securityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(CardDetailDTO)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class CardBalanceDTO
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private cardNumberField As String
        
        Private authorizationNumberField As String
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AuthorizationNumber() As String
            Get
                Return Me.authorizationNumberField
            End Get
            Set
                Me.authorizationNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class TestRequestDTO
        
        Private tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Request")>  _
    Partial Public Class CardGetListRequest
        
        Private filterField As CardGetListFilter
        
        Private filterFieldSpecified As Boolean
        
        Private filterValueField As String
        
        Private pagingField As PagingDTO
        
        Private securityField As SecurityDTO
        
        '''<remarks/>
        Public Property Filter() As CardGetListFilter
            Get
                Return Me.filterField
            End Get
            Set
                Me.filterField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FilterSpecified() As Boolean
            Get
                Return Me.filterFieldSpecified
            End Get
            Set
                Me.filterFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FilterValue() As String
            Get
                Return Me.filterValueField
            End Get
            Set
                Me.filterValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Paging() As PagingDTO
            Get
                Return Me.pagingField
            End Get
            Set
                Me.pagingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Security() As SecurityDTO
            Get
                Return Me.securityField
            End Get
            Set
                Me.securityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Public Enum CardGetListFilter
        
        '''<remarks/>
        None
        
        '''<remarks/>
        ByEmployerId
        
        '''<remarks/>
        ByCardNumber
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class PagingDTO
        
        Private allField As Boolean
        
        Private allFieldSpecified As Boolean
        
        Private pageNumberField As Integer
        
        Private pageNumberFieldSpecified As Boolean
        
        Private pageRecordsField As Integer
        
        Private pageRecordsFieldSpecified As Boolean
        
        Private totalRecordsField As Integer
        
        Private totalRecordsFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property All() As Boolean
            Get
                Return Me.allField
            End Get
            Set
                Me.allField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AllSpecified() As Boolean
            Get
                Return Me.allFieldSpecified
            End Get
            Set
                Me.allFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PageNumber() As Integer
            Get
                Return Me.pageNumberField
            End Get
            Set
                Me.pageNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PageNumberSpecified() As Boolean
            Get
                Return Me.pageNumberFieldSpecified
            End Get
            Set
                Me.pageNumberFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PageRecords() As Integer
            Get
                Return Me.pageRecordsField
            End Get
            Set
                Me.pageRecordsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PageRecordsSpecified() As Boolean
            Get
                Return Me.pageRecordsFieldSpecified
            End Get
            Set
                Me.pageRecordsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalRecords() As Integer
            Get
                Return Me.totalRecordsField
            End Get
            Set
                Me.totalRecordsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TotalRecordsSpecified() As Boolean
            Get
                Return Me.totalRecordsFieldSpecified
            End Get
            Set
                Me.totalRecordsFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class SecurityDTO
        
        Private externalClientIdField As String
        
        Private tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ExternalClientId() As String
            Get
                Return Me.externalClientIdField
            End Get
            Set
                Me.externalClientIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Request")>  _
    Partial Public Class CardBalanceAdjustmentRequest
        
        Private cardBalanceDTOListField() As CardBalanceDTO
        
        Private securityField As SecurityDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property CardBalanceDTOList() As CardBalanceDTO()
            Get
                Return Me.cardBalanceDTOListField
            End Get
            Set
                Me.cardBalanceDTOListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Security() As SecurityDTO
            Get
                Return Me.securityField
            End Get
            Set
                Me.securityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class ErrorDTO
        
        Private codeField As UInteger
        
        Private codeFieldSpecified As Boolean
        
        Private messageField As String
        
        Private typeErrorField As UInteger
        
        Private typeErrorFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Code() As UInteger
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CodeSpecified() As Boolean
            Get
                Return Me.codeFieldSpecified
            End Get
            Set
                Me.codeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TypeError() As UInteger
            Get
                Return Me.typeErrorField
            End Get
            Set
                Me.typeErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TypeErrorSpecified() As Boolean
            Get
                Return Me.typeErrorFieldSpecified
            End Get
            Set
                Me.typeErrorFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(CardGetListResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CardBalanceAdjustmentResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CardBalanceAssignmentResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Response")>  _
    Partial Public Class BaseResponse
        
        Private successField As Boolean
        
        Private successFieldSpecified As Boolean
        
        Private errorListField() As ErrorDTO
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessSpecified() As Boolean
            Get
                Return Me.successFieldSpecified
            End Get
            Set
                Me.successFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property ErrorList() As ErrorDTO()
            Get
                Return Me.errorListField
            End Get
            Set
                Me.errorListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Response")>  _
    Partial Public Class CardGetListResponse
        Inherits BaseResponse
        
        Private cardListField() As CardDetailDTO
        
        Private pagingField As PagingDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property CardList() As CardDetailDTO()
            Get
                Return Me.cardListField
            End Get
            Set
                Me.cardListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Paging() As PagingDTO
            Get
                Return Me.pagingField
            End Get
            Set
                Me.pagingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class CardDetailDTO
        Inherits CardBalanceDTO
        
        Private cardStatusField As CardStatusDTO
        
        Private cardNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CardStatus() As CardStatusDTO
            Get
                Return Me.cardStatusField
            End Get
            Set
                Me.cardStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CardName() As String
            Get
                Return Me.cardNameField
            End Get
            Set
                Me.cardNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
    Partial Public Class CardStatusDTO
        
        Private statusField As Integer
        
        Private statusFieldSpecified As Boolean
        
        Private statusDescriptionField As String
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property StatusDescription() As String
            Get
                Return Me.statusDescriptionField
            End Get
            Set
                Me.statusDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Response")>  _
    Partial Public Class CardBalanceAdjustmentResponse
        Inherits BaseResponse
        
        Private cardBalanceDTOListField() As CardBalanceDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property CardBalanceDTOList() As CardBalanceDTO()
            Get
                Return Me.cardBalanceDTOListField
            End Get
            Set
                Me.cardBalanceDTOListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities.Response")>  _
    Partial Public Class CardBalanceAssignmentResponse
        Inherits BaseResponse
        
        Private cardBalanceDTOListField() As CardBalanceDTO
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/ERMX.SSOServices.TE.Entities")>  _
        Public Property CardBalanceDTOList() As CardBalanceDTO()
            Get
                Return Me.cardBalanceDTOListField
            End Get
            Set
                Me.cardBalanceDTOListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CardBalanceAssignmentCompletedEventHandler(ByVal sender As Object, ByVal e As CardBalanceAssignmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CardBalanceAssignmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CardBalanceAssignmentResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CardBalanceAssignmentResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CardBalanceAdjustmentCompletedEventHandler(ByVal sender As Object, ByVal e As CardBalanceAdjustmentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CardBalanceAdjustmentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CardBalanceAdjustmentResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CardBalanceAdjustmentResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub CardGetListCompletedEventHandler(ByVal sender As Object, ByVal e As CardGetListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CardGetListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CardGetListResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CardGetListResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub TestToConsumeCompletedEventHandler(ByVal sender As Object, ByVal e As TestToConsumeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestToConsumeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BaseResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BaseResponse)
            End Get
        End Property
    End Class
End Namespace
