

set identity_insert reporte on
go
insert into reporte (id_reporte, nombre, descripcion, es_plan, tipo_reporte, es_activo) 
			 values (1017, 'Pedidos y Facturación Fibras', 'Pedidos y Facturación Fibras', 1, 1, 0)
go
set identity_insert reporte off
go



alter table concepto add id_relacion_concepto int

go

go

go
SET NOCOUNT ON
 
SET IDENTITY_INSERT [dbo].[concepto] ON
GO
 
 
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202081,'01-P-00','PEDIDOS',1017,NULL,740,0,0,NULL,0,1,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,74)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202082,'01-P-01','Mexico',1017,NULL,750,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,75)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202083,'01-P-02','Export',1017,NULL,760,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,76)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202084,'01-P-08','Intercompanies NUSA',1017,NULL,765,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1387)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202085,'01-P-09','Intercompanies NP',1017,NULL,766,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1388)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202086,'01-P-10','Intercompanies NI',1017,NULL,767,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1389)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202087,'01-P-11','Intercompanies NE',1017,NULL,768,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1390)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202088,'01-P-03','Intercompanies NB',1017,NULL,770,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,77)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202089,'01-P-04','Intercompanies NF',1017,NULL,780,202090,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,78)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202090,'01-P-05','TOTAL',1017,NULL,790,202091,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,79)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202091,'01-P-06','NETA',1017,NULL,800,0,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,80)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202092,'02-F-00','FACTURACION',1017,NULL,810,0,0,NULL,0,1,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,81)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202093,'02-F-01','Mexico',1017,NULL,820,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,82)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202094,'02-F-02','Export',1017,NULL,830,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,83)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202095,'01-F-08','Intercompanies NUSA',1017,NULL,835,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1391)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202096,'01-F-09','Intercompanies NP',1017,NULL,836,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1392)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202097,'01-F-10','Intercompanies NI',1017,NULL,837,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1393)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202098,'01-F-11','Intercompanies NE',1017,NULL,838,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1394)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202099,'02-F-03','Intercompanies NB',1017,NULL,840,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,84)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202100,'02-F-04','Intercompanies NF',1017,NULL,850,202101,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,85)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202101,'02-F-05','TOTAL',1017,NULL,860,202102,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,86)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202102,'02-F-06','NETA',1017,NULL,870,0,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,87)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202103,'03-B-00','BACKLOG',1017,NULL,880,0,0,NULL,0,1,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,88)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202104,'03-B-01','Mexico',1017,NULL,890,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,89)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202105,'03-B-02','Export',1017,NULL,900,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,90)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202106,'01-B-08','Intercompanies NUSA',1017,NULL,905,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1395)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202107,'01-B-09','Intercompanies NP',1017,NULL,906,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1396)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202108,'01-B-10','Intercompanies NI',1017,NULL,907,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1397)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202109,'01-B-11','Intercompanies NE',1017,NULL,908,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,1398)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202110,'03-B-03','Intercompanies NB',1017,NULL,910,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,91)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202111,'03-B-03b','Intercompanies NF',1017,NULL,915,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,112)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202112,'03-B-05','TOTAL',1017,NULL,920,202113,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,92)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202113,'03-B-06','NETA',1017,NULL,930,0,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,93)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202114,'03-B-00','TONELADAS VENDIDAS',1017,NULL,1030,0,0,NULL,0,1,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202115,'03-B-01','Mexico',1017,NULL,1040,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202116,'03-B-02','Export',1017,NULL,1050,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202117,'01-B-08','Intercompanies NUSA',1017,NULL,1055,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202118,'01-B-09','Intercompanies NP',1017,NULL,1056,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202119,'01-B-10','Intercompanies NI',1017,NULL,1057,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202120,'01-B-11','Intercompanies NE',1017,NULL,1058,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,2017,1,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202121,'03-B-03','Intercompanies NB',1017,NULL,1060,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202122,'03-B-03b','Intercompanies NF',1017,NULL,1065,202112,0,NULL,1,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202123,'03-B-05','TOTAL',1017,NULL,1070,202113,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)
INSERT INTO [concepto] ([id_concepto],[clave],[descripcion],[id_reporte],[id_grupo],[orden],[id_padre],[resta],[formula_especial],[permite_captura],[es_separador],[es_plan],[es_fibras],[es_hornos],[id_empresa],[descripcion_2],[anio_baja],[periodo_baja],[es_borrado],[referencia],[referencia2],[referencia3],[anio_alta],[periodo_alta],[id_relacion_concepto])VALUES(202124,'03-B-06','NETA',1017,NULL,1080,0,0,NULL,0,0,0,0,0,NULL,'',NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)

go 
SET IDENTITY_INSERT [dbo].[concepto] OFF
GO
SET NOCOUNT OFF
go

go

go

go

go

go
update concepto set id_padre = 202123 where id_concepto in (202115, 202116, 202117, 202118, 202119, 202120, 202121, 202122)
update concepto set id_padre = 202124 where id_concepto in (202123)
go

go




